### ISSUE TITLE
Édition des utilisateurs/groupes impossible

### ISSUE THREAD

**Issue by remche** [INRIA/osc#1]
Hello,
Depuis une installation fraîche (base peuplée par seeds), je ne peux éditer ni les groupe ni les utilisateurs.

Started GET "/users/1/edit" for ***.***.***.*** at 2017-02-09 09:32:28 +0000
Processing by UsersController#edit as HTML
  Parameters: {"id"=>"1"}
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  Role Load (0.2ms)  SELECT `roles`.* FROM `roles` INNER JOIN `roles_users` ON `roles`.`id` = `roles_users`.`role_id` WHERE `roles_users`.`user_id` = 1
  Group Load (0.2ms)  SELECT `groups`.* FROM `groups` INNER JOIN `memberships` ON `groups`.`id` = `memberships`.`group_id` WHERE `memberships`.`user_id` = 1
  CACHE (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  Group Load (0.2ms)  SELECT `groups`.* FROM `groups` INNER JOIN `memberships` ON `groups`.`id` = `memberships`.`group_id` WHERE `memberships`.`user_id` = 1 ORDER BY nom
  Group Load (0.1ms)  SELECT `groups`.* FROM `groups` ORDER BY nom
  SQL (0.2ms)  SELECT `memberships`.`id` AS t0_r0, `memberships`.`user_id` AS t0_r1, `memberships`.`group_id` AS t0_r2, `memberships`.`created_at` AS t0_r3, `memberships`.`updated_at` AS t0_r4, `groups`.`id` AS t1_r0, `groups`.`nom` AS t1_r1, `groups`.`description` AS t1_r2, `groups`.`created_at` AS t1_r3, `groups`.`updated_at` AS t1_r4 FROM `memberships` LEFT OUTER JOIN `groups` ON `groups`.`id` = `memberships`.`group_id` WHERE `memberships`.`user_id` = 1 ORDER BY groups.nom
  Projet Load (0.1ms)  SELECT `projets`.* FROM `projets` ORDER BY nom
Completed 500 Internal Server Error in 19.0ms

TypeError (no implicit conversion of nil into String):
  vendor/bundle/ruby/2.3.0/gems/arel-3.0.3/lib/arel.rb:40:in `initialize'
  vendor/bundle/ruby/2.3.0/gems/arel-3.0.3/lib/arel.rb:40:in `new'
  vendor/bundle/ruby/2.3.0/gems/arel-3.0.3/lib/arel.rb:40:in `sql'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/associations/join_helper.rb:47:in `block in sanitize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/associations/join_helper.rb:45:in `map'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/associations/join_helper.rb:45:in `sanitize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/associations/join_dependency/join_association.rb:104:in `block in join_to'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/associations/join_dependency/join_association.rb:74:in `each'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/associations/join_dependency/join_association.rb:74:in `each_with_index'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/associations/join_dependency/join_association.rb:74:in `join_to'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/query_methods.rb:370:in `block in build_joins'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/query_methods.rb:369:in `each'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/query_methods.rb:369:in `build_joins'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/query_methods.rb:266:in `build_arel'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/query_methods.rb:260:in `arel'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/delegation.rb:42:in `locked'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `locked?'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/query_cache.rb:59:in `select_all'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/finder_methods.rb:212:in `find_with_associations'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation.rb:171:in `exec_queries'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation.rb:160:in `block in to_a'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/explain.rb:41:in `logging_query_plan'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation.rb:159:in `to_a'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/finder_methods.rb:159:in `all'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/finder_methods.rb:105:in `find'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/relation/finder_methods.rb:101:in `find'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/querying.rb:5:in `find'
  app/controllers/users_controller.rb:316:in `prepare_edit_and_delete_droit'
  app/controllers/users_controller.rb:277:in `edit'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:480:in `_run__2574966535122790003__process_action__990061953070708787__callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/2.3.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/2.3.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/query_cache.rb:64:in `call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-3.2.22.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:405:in `_run__2398327824066408869__call__4564091989699863178__callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-3.2.22.3/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.3/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
  vendor/bundle/ruby/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:249:in `fetch'
  vendor/bundle/ruby/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:189:in `lookup'
  vendor/bundle/ruby/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:66:in `call!'
  vendor/bundle/ruby/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by remche** [comment]
À vrai dire, je ne peux pas créer de nouveaux contrats non plus. 

TypeError (no implicit conversion of nil into String):
…
  app/controllers/contrats_controller.rb:933:in `prepare_edit_and_update'
  app/controllers/contrats_controller.rb:320:in `edit'
…

**Comment by remche** [comment]
Après une recherche plus approndie, il semble que OSC n'est pas compatible avec ruby >= 2.3.
J'utilise 2.2 et c'est mieux.
Merci.
